### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by Elizabeth129** [Elizabeth129/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by ElizabethIvanytska** [comment]
Coment

**Comment by Elizabeth129** [comment]
Close

**Comment by ElizabethIvanytska** [comment]
I do not compete with others, the only competition that challenges me is myself. As a fighter, friend and an employee I am known as contemplative, tortured and driven.
